### PR TITLE
Upgrade from Yarn Classic to Yarn Modern

### PR DESCRIPTION
**Pull request by Jayman2000**
Before this change, the instructions in the README were wrong. The instructions in the README told users that they had to have Yarn installed, and they linked to the Web site for Yarn Modern. Unfortunately, package.json said this:

```json
  "packageManager": "yarn@1.22.22+sha512.a6b2f7906b721bba3d67d4aff083df04dad64c399707841b7acf00f6b133b7ac24255f2652fa22ae3534329dc6180534e98d17432037ff6fd140556e2bb3137e"
```

That Yarn version 1.22.22 is a version of Yarn Classic, not a version of Yarn Modern. If you use Yarn Modern (like the README says to do), then it will automatically make a bunch of changes that are unrelated to whatever you’re doing.

In order to fix this issue, this commit updates the repo to use Yarn Modern instead of Yarn Classic. We probably should have been using Yarn Modern to begin with.

Partially addresses #7.

### CODE REVIEW

**Comment by ohadmamet** [comment]
Checks seem to fail with:
  Error: The lockfile would have been modified by this install, which is explicitly forbidden. (YN0028)

Does setup-yarn-action need a yarn version specified? I am unfamiliar with it.

**Comment by Jayman2000** [comment]
> Does setup-yarn-action need a yarn version specified? I am unfamiliar with it.

I don’t think so. [The README for Setup Yarn Berry says:](https://github.com/threeal/setup-yarn-action/tree/v2.0.0?tab=readme-ov-file#specifying-yarn-version)

> By default, this action will set up Yarn to the default version specified by the current Node.js project.
> However, you can override it by specifying it in the `version` input parameter as shown below:

**Comment by Jayman2000** [comment]
> Checks seem to fail with:
> Error: The lockfile would have been modified by this install, which is explicitly forbidden. (YN0028)

I figured out what the problem was. I used Yarn 4.2.2 because [that’s the version that NixOS 24.05 ships at the moment](https://github.com/NixOS/nixpkgs/blob/4a92571f9207810b559c9eac203d1f4d79830073/pkgs/development/tools/yarn-berry/default.nix#L5). When I used Yarn 4.2.2 to upgrade the repo, it put this in `package.json`:

```json
  "packageManager": "yarn@4.4.0"
```

It seems kind of weird that Yarn 4.2.2 would upgrade us to Yarn 4.4.0. I was able to do this in order to get a shell with Yarn 4.4.0 on NixOS:

1. Create a file named `shell.nix` that contains this:

	```nix
	let
	  pkgs = import <nixpkgs> { };
	  # This is the version of Nixpkgs from this PR:
	  # <https://github.com/NixOS/nixpkgs/pull/332104>.
	  pr332104Repo = pkgs.fetchFromGitHub {
	    owner = "r-ryantm";
	    repo = "nixpkgs";
	    rev = "auto-update/yarn-berry";
	    hash = "sha256-u5d3ovQzKIm0QC4dWgpk3tzmFYfU2L5g2iUgQa+HsO8=";
	  };
	  pr332104Pkgs = import pr332104Repo { };
	in
	
	pkgs.mkShellNoCC {
	  name = "shell-for-smartkidsllc-github-io";
	  packages = [
	    pr332104Pkgs.yarn-berry
	  ];
	}
	```

2. `cd` into the directory that contains `shell.nix`.

3. Run `nix-shell`.

Once I was running Yarn 4.4.0, I generated a new `yarn.lock` file, and the test deployment workflow started working.

**Comment by ohadmamet** [comment]
Do we want to add in instructions to set yarn to berry in case it is not setup in the README.md instructions?

something like `yarn set version latest`?

**Comment by Jayman2000** [comment]
> Do we want to add in instructions to set yarn to berry in case it is not setup in the README.md instructions?

I think that the instructions are good enough at the moment.

> something like `yarn set version latest`?

I don’t think that it makes sense to tell users to run `yarn set version latest`. [According to the Yarn docs, `yarn set version` locks the project to a specific version of Yarn.](https://yarnpkg.com/cli/set/version) This PR already locks us to a specific version of Yarn by including this in `pakcage.json`:

```json
  "packageManager": "yarn@4.4.0"
```

I do think that we should update the instructions in the README so that they tell users how to install the correct version of Yarn, but I want to do that in a separate PR. I have a lot of ideas for how the instructions in the README could be improved, but I don’t want the changes in this PR to wait until after some of those ideas have been polished and reviewed. In my experience, creating and reviewing [pull requests that](https://github.com/DescentDevelopers/Descent3/pull/413) [modify build instructions](https://github.com/DescentDevelopers/Descent3/pull/469) can take a long time.

I don’t want the changes in this PR to wait because we need the changes in this PR in order to submit and review other PRs. I suppose that I could test other PRs using Yarn Classic, but I think that it’s important to follow the build instructions in the README when testing a pull request. If I don’t follow the build instructions as they’re written, then how do I know that the PR actually works properly? I suppose that I could also ignore #7 when testing other PRs, but that also sounds like a bad idea. If I ignore #7, then how do I know whether or not there was an automated change that should have been committed?

**Review by ohadmamet — APPROVED** [review]
lgtm

**Pull request merged**
